// Generates web/js/config.js: the Supabase endpoint, and the writable-column
// map the shim uses to drop view-only columns before an insert or update.
const fs = require('fs');
const path = require('path');
const { ROOT, env, runSql } = require('./env');

const SQL = `select table_name, string_agg(column_name, ',' order by ordinal_position) cols
             from information_schema.columns
             where table_schema='public' and is_generated='NEVER'
             group by table_name order by 1`;

runSql(SQL).then(list => {
  const map = {};
  for (const r of list) map[r.table_name] = r.cols.split(',');
  // Only the anon key goes in here. It is public by design — RLS is what
  // protects the data, not the key.
  const out = `// Generated by tools/tools-columns.js — do not edit by hand.
window.__SUPABASE_URL__  = ${JSON.stringify(env.SUPABASE_URL)};
window.__SUPABASE_ANON__ = ${JSON.stringify(env.ANON)};
window.__TRIAL_EMAIL__    = ${JSON.stringify(env.TRIAL_EMAIL || '')};
window.__WRITABLE_COLUMNS__ = ${JSON.stringify(map, null, 0)};
`;
  fs.writeFileSync(path.join(ROOT, 'web/js/config.js'), out);
  console.log('config.js written,', Object.keys(map).length, 'tables');
}).catch(e => { console.error(e.message); process.exit(1); });
