CREATE TABLE areas (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_en    text NOT NULL,
    name_ar    text,
    sort_order bigint NOT NULL DEFAULT 0,
    active     bigint NOT NULL DEFAULT 1,
    created_at text NOT NULL DEFAULT now_cairo()
, zone_id bigint);

CREATE TABLE chemicals (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_en           text NOT NULL,
    name_ar           text,
    active_ingredient text,
    unit              text NOT NULL DEFAULT 'L',
    quantity_in_stock double precision NOT NULL DEFAULT 0,
    reorder_level     double precision NOT NULL DEFAULT 0,
    hazard_class      text,
    reg_no            text,
    cost_per_unit     double precision NOT NULL DEFAULT 0,
    created_at        text NOT NULL DEFAULT now_cairo()
, material_key text, expiry_date text);

CREATE TABLE clients (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_en        text NOT NULL,
    name_ar        text,
    contact_person text,
    phone          text,
    email          text,
    address_en     text,
    address_ar     text,
    city           text,
    notes          text,
    status         text NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')),
    created_at     text NOT NULL DEFAULT now_cairo()
, dunning bigint NOT NULL DEFAULT 1, area_id bigint);

CREATE TABLE price_book (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_en     text NOT NULL,
    name_ar     text,
    description text,
    unit_price  double precision NOT NULL DEFAULT 0,
    active      bigint NOT NULL DEFAULT 1,
    created_at  text NOT NULL DEFAULT now_cairo()
);

CREATE TABLE report_options (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind       text NOT NULL CHECK (kind IN ('condition','recommendation')),
    name_en    text NOT NULL,
    name_ar    text,
    sort_order bigint NOT NULL DEFAULT 0,
    active     bigint NOT NULL DEFAULT 1,
    created_at text NOT NULL DEFAULT now_cairo()
);

CREATE TABLE role_permissions (
    role    text NOT NULL CHECK (role IN ('admin','manager','agent','client')),
    perm    text NOT NULL,
    allowed bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (role, perm)
);

CREATE TABLE service_types (
    id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_en text NOT NULL,
    name_ar text
);

CREATE TABLE settings (
    key   text PRIMARY KEY,
    value text
);

CREATE TABLE shift_types (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       text NOT NULL UNIQUE,
    name_en    text NOT NULL,
    name_ar    text,
    start_time text,                              -- 'HH:MM' (NULL for off/leave)
    end_time   text,
    color      text NOT NULL DEFAULT '#1f74d6',
    is_off     bigint NOT NULL DEFAULT 0,
    active     bigint NOT NULL DEFAULT 1,
    sort_order bigint NOT NULL DEFAULT 0
, open_ended bigint NOT NULL DEFAULT 0);

CREATE TABLE translations (
    src_hash   text NOT NULL,
    target     text NOT NULL,
    src_lang   text,
    text       text NOT NULL,
    created_at text NOT NULL DEFAULT now_cairo(),
    PRIMARY KEY (src_hash, target)
);

CREATE TABLE zones (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_en    text NOT NULL,
    name_ar    text,
    sort_order bigint NOT NULL DEFAULT 0,
    active     bigint NOT NULL DEFAULT 1,
    created_at text NOT NULL DEFAULT now_cairo()
, own_day bigint NOT NULL DEFAULT 0);

CREATE TABLE "inventory_transactions" (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                chemical_id bigint NOT NULL REFERENCES chemicals(id) ON DELETE CASCADE,
                change double precision NOT NULL,
                reason text NOT NULL CHECK (reason IN ('purchase','usage','adjustment','issue')),
                reference text, note text,
                created_at text NOT NULL DEFAULT now_cairo());

CREATE TABLE sites (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id  bigint NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    name       text NOT NULL,
    address    text,
    area       text,
    created_at text NOT NULL DEFAULT now_cairo()
, map_image text, lat double precision, lng double precision, area_id bigint, service_from text, service_to text, visits_per_month double precision NOT NULL DEFAULT 0, visit_minutes bigint, freq_unit text NOT NULL DEFAULT 'week', visits_per_week double precision NOT NULL DEFAULT 0, preferred_agent_id bigint, status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')), map_url text);

CREATE TABLE devices (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       text NOT NULL UNIQUE,           -- e.g. LIT0001 (printed as the QR)
    type       text NOT NULL,                  -- light_trap|glue_station|bait_station|fly_trap
    client_id  bigint REFERENCES clients(id) ON DELETE SET NULL,
    site_id    bigint REFERENCES sites(id) ON DELETE SET NULL,
    label      text,                           -- optional friendly location ("Kitchen")
    status     text NOT NULL DEFAULT 'ok',     -- last-known: ok|activity|needs_service|missing
    active     bigint NOT NULL DEFAULT 1,
    created_at text NOT NULL DEFAULT now_cairo()
, placement text);

CREATE TABLE site_service_days (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id    bigint NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
    weekday    bigint NOT NULL CHECK (weekday BETWEEN 0 AND 6),
    start_time text,                              -- NULL = the branch's usual window
    end_time   text, agent_id bigint,
    UNIQUE (site_id, weekday)
);

CREATE TABLE "users" (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                full_name text NOT NULL,
                email text NOT NULL UNIQUE,
                password_hash text NOT NULL,
                role text NOT NULL
                    CHECK (role IN ('admin','manager','agent','area_manager','team_leader','client')),
                phone text,
                client_id bigint REFERENCES clients(id) ON DELETE SET NULL,
                site_id bigint REFERENCES sites(id) ON DELETE SET NULL,
                team_leader_id bigint REFERENCES users(id) ON DELETE SET NULL,
                specialization text, hire_date text,
                license_no text, license_expiry text,
                lang text NOT NULL DEFAULT 'en',
                active bigint NOT NULL DEFAULT 1,
                token_version bigint NOT NULL DEFAULT 0,
                created_at text NOT NULL DEFAULT now_cairo());

CREATE TABLE agent_areas (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id   bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    area_id    bigint NOT NULL REFERENCES areas(id) ON DELETE CASCADE,
    created_at text NOT NULL DEFAULT now_cairo(), weekdays text,
    UNIQUE (agent_id, area_id)
);

CREATE TABLE "agent_availability" (
            id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            agent_id   bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            weekday    bigint NOT NULL CHECK (weekday BETWEEN 0 AND 6),
            start_time text,
            end_time   text
        );

CREATE TABLE agent_shifts (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id      bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    shift_date    text NOT NULL,                  -- 'YYYY-MM-DD'
    shift_type_id bigint NOT NULL REFERENCES shift_types(id) ON DELETE CASCADE,
    start_time    text,
    end_time      text,
    note          text,
    assigned_by   bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at    text NOT NULL DEFAULT now_cairo()
, area_id bigint);

CREATE TABLE area_manager_areas (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manager_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    area_id    bigint NOT NULL REFERENCES areas(id) ON DELETE CASCADE,
    created_at text NOT NULL DEFAULT now_cairo(),
    UNIQUE (manager_id, area_id)
);

CREATE TABLE audit_log (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint REFERENCES users(id) ON DELETE SET NULL,
    user_name   text,                          -- denormalized for history
    action      text NOT NULL,                 -- e.g. invoice.create
    entity      text,                          -- e.g. invoice
    entity_id   text,
    detail      text,                          -- short human-readable note
    ip          text,
    created_at  text NOT NULL DEFAULT now_cairo()
);

CREATE TABLE company_files (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         text NOT NULL,
    description   text,
    filename      text NOT NULL,
    original_name text,
    size_bytes    bigint NOT NULL DEFAULT 0,
    visible_to_clients bigint NOT NULL DEFAULT 1,
    uploaded_by   bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at    text NOT NULL DEFAULT now_cairo(),
    updated_at    text
);

CREATE TABLE cost_budgets (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category   text NOT NULL,
    year       text NOT NULL,                 -- 'YYYY'
    period     text NOT NULL DEFAULT 'monthly' CHECK (period IN ('monthly','annual')),
    amount     double precision NOT NULL DEFAULT 0,
    note       text,
    created_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at text NOT NULL DEFAULT now_cairo(),
    updated_at text,
    UNIQUE (category, year)
);

CREATE TABLE cost_recurring (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       text NOT NULL,
    category   text NOT NULL DEFAULT 'other',
    amount     double precision NOT NULL DEFAULT 0,
    frequency  text NOT NULL DEFAULT 'monthly',
    start_date text NOT NULL,
    next_due   text,                        -- NULL = nothing more to post
    end_date   text,
    user_id    bigint REFERENCES users(id) ON DELETE SET NULL,  -- whose salary
    vendor     text,
    note       text,
    auto_post  bigint NOT NULL DEFAULT 1,  -- 0 = remind me, I will post it
    active     bigint NOT NULL DEFAULT 1,
    created_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at text NOT NULL DEFAULT now_cairo(),
    updated_at text
);

CREATE TABLE engineer_issues (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id    bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    note        text,
    created_by  bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at  text NOT NULL DEFAULT now_cairo()
, status text NOT NULL DEFAULT 'approved' CHECK (status IN ('requested','approved','declined')), handled_by bigint, handled_at text, decline_reason text, receipt_status text, receipt_at text, receipt_note text);

CREATE TABLE fixed_assignments (
        id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        site_id          bigint NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
        primary_agent_id bigint NOT NULL REFERENCES users(id),
        relief_agent_id  bigint REFERENCES users(id),
        primary_weekdays text NOT NULL DEFAULT '',
        relief_weekdays  text NOT NULL DEFAULT '',
        from_time        text NOT NULL,
        to_time          text NOT NULL,
        start_date       text,
        end_date         text,
        active           bigint NOT NULL DEFAULT 1,
        created_at       text NOT NULL DEFAULT now_cairo()
);

CREATE TABLE leads (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           text NOT NULL,
    company        text,
    phone          text,
    email          text,
    sector         text,
    message        text,
    preferred_date text,
    source         text NOT NULL DEFAULT 'manual',
    status         text NOT NULL DEFAULT 'new'
                   CHECK (status IN ('new','contacted','quoted','won','lost')),
    note           text,
    client_id      bigint REFERENCES clients(id) ON DELETE SET NULL,
    handled_by     bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at     text NOT NULL DEFAULT now_cairo(),
    updated_at     text
);

CREATE TABLE maps (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id   bigint NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    site_id     bigint REFERENCES sites(id) ON DELETE SET NULL,
    name        text NOT NULL,
    filename    text NOT NULL,
    uploaded_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at  text NOT NULL DEFAULT now_cairo()
);

CREATE TABLE marketing_targets (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    period           text NOT NULL,               -- 'YYYY-MM'
    target_amount    double precision NOT NULL DEFAULT 0,     -- contract value per month
    target_contracts bigint NOT NULL DEFAULT 0,  -- 0 = not counted
    note             text,
    created_by       bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at       text NOT NULL DEFAULT now_cairo(),
    updated_at       text
);

CREATE TABLE material_returns (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id    bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    note        text,
    created_by  bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at  text NOT NULL DEFAULT now_cairo(),
    status      text NOT NULL DEFAULT 'requested'
                CHECK (status IN ('requested','approved','declined')),
    handled_by  bigint REFERENCES users(id) ON DELETE SET NULL,
    handled_at  text,
    decline_reason text,
    receipt_status text,          -- NULL | 'received' | 'disputed'
    receipt_at     text,
    receipt_by     bigint REFERENCES users(id) ON DELETE SET NULL,
    receipt_note   text
);

CREATE TABLE notification_prefs (
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    grp     text NOT NULL,
    enabled bigint NOT NULL DEFAULT 1,
    UNIQUE (user_id, grp)
);

CREATE TABLE notifications (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     bigint REFERENCES users(id) ON DELETE CASCADE,
    type        text NOT NULL,
    title       text NOT NULL,
    body        text,
    link_view   text,
    link_id     bigint,
    is_read     bigint NOT NULL DEFAULT 0,
    dedup_key   text,
    created_at  text NOT NULL DEFAULT now_cairo()
);

CREATE TABLE "photos" (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                entity_type text NOT NULL
                    CHECK (entity_type IN ('client','report','visit','chemical','expense','cash')),
                entity_id bigint NOT NULL,
                filename text NOT NULL, original_name text, caption text,
                is_business_plan bigint NOT NULL DEFAULT 0,
                uploaded_by bigint REFERENCES users(id) ON DELETE SET NULL,
                uploaded_at text NOT NULL DEFAULT now_cairo());

CREATE TABLE purchase_orders (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier    text,
    reference   text,
    note        text,
    total_cost  double precision NOT NULL DEFAULT 0,
    created_by  bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at  text NOT NULL DEFAULT now_cairo()
);

CREATE TABLE roster_runs (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_date  text NOT NULL,
    to_date    text NOT NULL,
    created_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at text NOT NULL DEFAULT now_cairo(),
    visits     bigint NOT NULL DEFAULT 0,   -- booked outright
    assigned   bigint NOT NULL DEFAULT 0,   -- existing visits given an engineer
    shifts     bigint NOT NULL DEFAULT 0,
    undone_at  text,
    undone_by  bigint REFERENCES users(id) ON DELETE SET NULL,
    kept       bigint NOT NULL DEFAULT 0    -- rows an undo refused to touch
, cleared_at text, cleared_by bigint, cleared_visits bigint NOT NULL DEFAULT 0, cleared_shifts bigint NOT NULL DEFAULT 0);

CREATE TABLE user_permissions (
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    perm    text NOT NULL,
    allowed bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id, perm)
);

CREATE TABLE user_prefs (
        user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        key     text NOT NULL,
        value   text,
        PRIMARY KEY (user_id, key)
    );

CREATE TABLE engineer_issue_items (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id    bigint NOT NULL REFERENCES engineer_issues(id) ON DELETE CASCADE,
    chemical_id bigint NOT NULL REFERENCES chemicals(id) ON DELETE CASCADE,
    quantity    double precision NOT NULL
, approved_quantity double precision, line_status text);

CREATE TABLE expenses (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spent_on     text NOT NULL,             -- 'YYYY-MM-DD'
    category     text NOT NULL DEFAULT 'other',
    description  text,
    amount       double precision NOT NULL DEFAULT 0,
    vendor       text,
    method       text,                      -- cash / bank / card …
    reference    text,
    user_id      bigint REFERENCES users(id) ON DELETE SET NULL,
    recurring_id bigint REFERENCES cost_recurring(id) ON DELETE SET NULL,
    source       text NOT NULL DEFAULT 'manual',   -- manual | recurring
    note         text,
    created_by   bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at   text NOT NULL DEFAULT now_cairo(),
    updated_at   text
);

CREATE TABLE map_markers (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_id     bigint NOT NULL REFERENCES maps(id) ON DELETE CASCADE,
    type       text NOT NULL DEFAULT 'other',
    label      text,
    x          double precision NOT NULL,
    y          double precision NOT NULL,
    status     text NOT NULL DEFAULT 'ok',
    notes      text,
    created_at text NOT NULL DEFAULT now_cairo()
, qr_token text);

CREATE TABLE material_return_items (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_id   bigint NOT NULL REFERENCES material_returns(id) ON DELETE CASCADE,
    chemical_id bigint NOT NULL REFERENCES chemicals(id) ON DELETE CASCADE,
    quantity    double precision NOT NULL,
    -- What the office agreed to take back, line by line — same shape as an
    -- issue's approved_quantity, so a line can be cut or refused on its own.
    approved_quantity double precision,
    line_status text CHECK (line_status IS NULL OR line_status IN ('approved','declined'))
);

CREATE TABLE purchase_order_items (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_id       bigint NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
    chemical_id bigint NOT NULL REFERENCES chemicals(id) ON DELETE CASCADE,
    quantity    double precision NOT NULL,
    unit_cost   double precision NOT NULL DEFAULT 0
);

CREATE TABLE roster_run_items (
    run_id   bigint NOT NULL REFERENCES roster_runs(id) ON DELETE CASCADE,
    kind     text NOT NULL CHECK (kind IN ('visit_created','visit_assigned','shift_created')),
    ref_id   bigint NOT NULL,
    agent_id bigint
);

CREATE TABLE roster_run_unplaced (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id     bigint NOT NULL REFERENCES roster_runs(id) ON DELETE CASCADE,
    visit_date text NOT NULL,
    site_id    bigint REFERENCES sites(id) ON DELETE CASCADE,
    area_id    bigint REFERENCES areas(id) ON DELETE SET NULL,
    minutes    bigint,
    reason     text NOT NULL,
    dismissed_at text,                     -- "dealt with another way", by hand
    dismissed_by bigint REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE marker_events (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marker_id   bigint NOT NULL REFERENCES map_markers(id) ON DELETE CASCADE,
    map_id      bigint NOT NULL REFERENCES maps(id) ON DELETE CASCADE,
    client_id   bigint REFERENCES clients(id) ON DELETE CASCADE,
    type        text,                       -- device type at time of record
    status      text NOT NULL,              -- ok / needs_service / activity / missing
    note        text,
    recorded_by bigint REFERENCES users(id) ON DELETE SET NULL,
    recorded_at text NOT NULL DEFAULT now_cairo()
, source text NOT NULL DEFAULT 'manual', lat double precision, lng double precision);

CREATE TABLE vat_returns (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period       text NOT NULL UNIQUE,          -- '2026-06' or '2026-Q2'
    period_start text NOT NULL,
    period_end   text NOT NULL,
    due_date     text NOT NULL,
    output_vat   double precision NOT NULL DEFAULT 0,       -- charged on invoices issued
    input_vat    double precision NOT NULL DEFAULT 0,       -- reclaimable, entered by the owner
    status       text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','paid')),
    expense_id   bigint REFERENCES expenses(id) ON DELETE SET NULL,
    note         text,
    created_at   text NOT NULL DEFAULT now_cairo(),
    updated_at   text
);

CREATE TABLE chemical_usage (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id bigint NOT NULL,
    chemical_id  bigint NOT NULL REFERENCES chemicals(id) ON DELETE CASCADE,
    quantity     double precision NOT NULL,
    area_treated text,
    created_at   text NOT NULL DEFAULT now_cairo()
, method text, equipment text);

CREATE TABLE contract_sites (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id bigint NOT NULL,
    site_id      bigint REFERENCES sites(id) ON DELETE SET NULL,
    map_location text,
    price        double precision NOT NULL DEFAULT 0
);

CREATE TABLE contracts (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id       bigint NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    site_id         bigint REFERENCES sites(id) ON DELETE SET NULL,
    service_type_id bigint REFERENCES service_types(id) ON DELETE SET NULL,
    agent_id        bigint REFERENCES users(id) ON DELETE SET NULL,
    frequency       text NOT NULL DEFAULT 'monthly'
                    CHECK (frequency IN ('weekly','biweekly','monthly','quarterly','semiannual','annual')),
    start_date      text NOT NULL,
    end_date        text,
    next_run_date   text NOT NULL,
    price           double precision NOT NULL DEFAULT 0,
    status          text NOT NULL DEFAULT 'active'
                    CHECK (status IN ('active','paused','ended')),
    notes           text,
    created_at      text NOT NULL DEFAULT now_cairo()
, bill_every text, next_bill_date text, auto_invoice bigint NOT NULL DEFAULT 0, quote_id bigint, sold_by bigint REFERENCES users(id) ON DELETE SET NULL, commission_rate double precision);

CREATE TABLE visits (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id       bigint NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    site_id         bigint REFERENCES sites(id) ON DELETE SET NULL,
    agent_id        bigint REFERENCES users(id) ON DELETE SET NULL,
    service_type_id bigint REFERENCES service_types(id) ON DELETE SET NULL,
    scheduled_start text NOT NULL,
    scheduled_end   text,
    status          text NOT NULL DEFAULT 'scheduled'
                    CHECK (status IN ('scheduled','in_progress','completed','cancelled')),
    location        text,
    notes           text,
    created_at      text NOT NULL DEFAULT now_cairo(),
    completed_at    text
, visit_number bigint, checkin_at text, checkin_lat double precision, checkin_lng double precision, checkin_acc double precision, checkout_at text, checkout_lat double precision, checkout_lng double precision, checkout_acc double precision, contract_id bigint REFERENCES contracts(id) ON DELETE SET NULL);

CREATE TABLE device_inspections (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id   bigint NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    visit_id    bigint REFERENCES visits(id) ON DELETE SET NULL,
    client_id   bigint REFERENCES clients(id) ON DELETE CASCADE,
    status      text NOT NULL,                 -- ok|activity|needs_service|missing
    findings    text,                          -- what the agent recorded for this device
    note        text,
    source      text NOT NULL DEFAULT 'scan',
    lat         double precision,
    lng         double precision,
    recorded_by bigint REFERENCES users(id) ON DELETE SET NULL,
    recorded_at text NOT NULL DEFAULT now_cairo()
, details text);

CREATE TABLE invoices (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id   bigint NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    visit_id    bigint REFERENCES visits(id) ON DELETE SET NULL,
    contract_id bigint REFERENCES contracts(id) ON DELETE SET NULL,
    doc_type    text NOT NULL DEFAULT 'invoice',   -- 'invoice' | 'quote'
    number      text NOT NULL,
    issue_date  text NOT NULL,
    due_date    text,
    valid_until text,                               -- quotes
    amount      double precision NOT NULL DEFAULT 0,
    tax         double precision NOT NULL DEFAULT 0,
    total       double precision NOT NULL DEFAULT 0,
    status      text NOT NULL DEFAULT 'draft',
    notes       text,
    created_at  text NOT NULL DEFAULT now_cairo()
, site_id bigint);

CREATE TABLE petty_cash (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id    bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    kind        text NOT NULL CHECK (kind IN ('advance','expense','return')),
    amount      double precision NOT NULL,
    -- expenses only: transport | purchase | repair | other
    category    text,
    spent_on    text NOT NULL DEFAULT today_cairo(),
    note        text,
    visit_id    bigint REFERENCES visits(id) ON DELETE SET NULL,
    -- An engineer's claim starts pending; anything the office records itself is
    -- approved as it is written.
    status      text NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending','approved','declined')),
    created_by  bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at  text NOT NULL DEFAULT now_cairo(),
    handled_by  bigint REFERENCES users(id) ON DELETE SET NULL,
    handled_at  text,
    decline_reason text
);

CREATE TABLE reports (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id        bigint NOT NULL UNIQUE REFERENCES visits(id) ON DELETE CASCADE,
    summary         text,
    pests_found     text,
    findings        text,
    recommendations text,
    severity        text DEFAULT 'low' CHECK (severity IN ('low','medium','high','critical')),
    next_visit_due  text,
    customer_name        text,
    customer_signature   text,   -- filename of captured signature image
    technician_signature text,
    created_at      text NOT NULL DEFAULT now_cairo()
, spare_parts_changed text, lamps_used double precision NOT NULL DEFAULT 0, cables_used double precision NOT NULL DEFAULT 0, transformers_used double precision NOT NULL DEFAULT 0, light_sheets_used double precision NOT NULL DEFAULT 0, fipronil_ml double precision NOT NULL DEFAULT 0, imidacloprid_gm double precision NOT NULL DEFAULT 0, baits_count double precision NOT NULL DEFAULT 0, glo_pieces double precision NOT NULL DEFAULT 0, flybase_bags double precision NOT NULL DEFAULT 0, branch_issue text, status text NOT NULL DEFAULT 'draft', completed_at text, transport_vehicle text, transport_cost double precision NOT NULL DEFAULT 0, condition text);

CREATE TABLE transport_entries (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id   bigint NOT NULL REFERENCES visits(id) ON DELETE CASCADE,
    vehicle    text,
    cost       double precision NOT NULL DEFAULT 0,
    created_by bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at text NOT NULL DEFAULT now_cairo()
, from_place text, to_place text);

CREATE TABLE visit_ratings (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id    bigint NOT NULL UNIQUE REFERENCES visits(id) ON DELETE CASCADE,
    client_id   bigint NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    stars       bigint NOT NULL CHECK (stars BETWEEN 1 AND 5),
    comment     text,
    created_by  bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at  text NOT NULL DEFAULT now_cairo()
);

CREATE TABLE visit_requests (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id      bigint NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    site_id        bigint REFERENCES sites(id) ON DELETE SET NULL,
    preferred_date text,
    note           text,
    status         text NOT NULL DEFAULT 'pending'
                   CHECK (status IN ('pending','approved','declined')),
    visit_id       bigint REFERENCES visits(id) ON DELETE SET NULL,
    created_by     bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at     text NOT NULL DEFAULT now_cairo(),
    handled_by     bigint REFERENCES users(id) ON DELETE SET NULL,
    handled_at     text
);

CREATE TABLE invoice_items (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id  bigint NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
    description text NOT NULL,
    quantity    double precision NOT NULL DEFAULT 1,
    unit_price  double precision NOT NULL DEFAULT 0,
    amount      double precision NOT NULL DEFAULT 0
);

CREATE TABLE payments (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id bigint NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
    amount     double precision NOT NULL,
    method     text NOT NULL DEFAULT 'cash',
    paid_at    text NOT NULL DEFAULT now_cairo(),
    note       text
);

CREATE TABLE payment_intents (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id   bigint NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
    client_id    bigint REFERENCES clients(id) ON DELETE SET NULL,
    provider     text NOT NULL,
    provider_ref text,
    token        text NOT NULL UNIQUE,
    amount       double precision NOT NULL,
    currency     text NOT NULL DEFAULT 'EGP',
    status       text NOT NULL DEFAULT 'pending'
                 CHECK (status IN ('pending','paid','failed','cancelled')),
    payment_id   bigint REFERENCES payments(id) ON DELETE SET NULL,
    created_at   text NOT NULL DEFAULT now_cairo(),
    updated_at   text
);

-- Circular foreign keys, added after every table exists
ALTER TABLE chemical_usage ADD CONSTRAINT chemical_usage_visit_id_fkey
    FOREIGN KEY (visit_id) REFERENCES visits(id) ON DELETE CASCADE;

ALTER TABLE contract_sites ADD CONSTRAINT contract_sites_contract_id_fkey
    FOREIGN KEY (contract_id) REFERENCES contracts(id) ON DELETE CASCADE;

CREATE INDEX idx_agent_areas_agent ON agent_areas(agent_id);
CREATE INDEX idx_agent_avail_agent ON agent_availability(agent_id);
CREATE INDEX idx_agent_shifts_agent_day ON agent_shifts(agent_id, shift_date);
CREATE INDEX idx_agent_shifts_date ON agent_shifts(shift_date);
CREATE INDEX idx_am_areas_area ON area_manager_areas(area_id);
CREATE INDEX idx_am_areas_manager ON area_manager_areas(manager_id);
CREATE INDEX idx_areas_order ON areas(sort_order, id);
CREATE INDEX idx_audit_created ON audit_log(created_at);
CREATE INDEX idx_avail_agent ON agent_availability(agent_id, weekday);
CREATE INDEX idx_cash_agent ON petty_cash(agent_id, status);
CREATE INDEX idx_company_files_filename ON company_files(filename);
CREATE INDEX idx_contract_sites_contract ON contract_sites(contract_id);
CREATE INDEX idx_contracts_client ON contracts(client_id);
CREATE INDEX idx_contracts_sold_by ON contracts(sold_by);
CREATE INDEX idx_cost_recurring_due ON cost_recurring(next_due);
CREATE INDEX idx_devices_client ON devices(client_id);
CREATE INDEX idx_devices_type ON devices(type);
CREATE INDEX idx_dinsp_device ON device_inspections(device_id);
CREATE INDEX idx_dinsp_visit ON device_inspections(visit_id);
CREATE INDEX idx_expenses_cycle ON expenses(recurring_id, spent_on);
CREATE INDEX idx_expenses_date ON expenses(spent_on);
CREATE INDEX idx_fixed_site ON fixed_assignments(site_id, active);
CREATE INDEX idx_invoices_client ON invoices(client_id);
CREATE INDEX idx_issue_items ON engineer_issue_items(issue_id);
CREATE INDEX idx_issues_agent ON engineer_issues(agent_id);
CREATE INDEX idx_items_invoice ON invoice_items(invoice_id);
CREATE INDEX idx_leads_status ON leads(status);
CREATE INDEX idx_maps_client ON maps(client_id);
CREATE INDEX idx_marker_events_client ON marker_events(client_id, recorded_at);
CREATE INDEX idx_marker_events_marker ON marker_events(marker_id);
CREATE INDEX idx_markers_map ON map_markers(map_id);
CREATE INDEX idx_notif_user ON notifications(user_id, is_read);
CREATE INDEX idx_payment_intents_invoice ON payment_intents(invoice_id);
CREATE INDEX idx_photos_entity ON photos(entity_type, entity_id);
CREATE INDEX idx_photos_filename ON photos(filename);
CREATE INDEX idx_report_options_kind ON report_options(kind, sort_order);
CREATE INDEX idx_return_items ON material_return_items(return_id);
CREATE INDEX idx_returns_agent ON material_returns(agent_id);
CREATE INDEX idx_roster_run_items_run ON roster_run_items(run_id);
CREATE INDEX idx_roster_run_unplaced_run ON roster_run_unplaced(run_id);
CREATE INDEX idx_site_service_days_site ON site_service_days(site_id);
CREATE INDEX idx_visit_requests_client ON visit_requests(client_id);
CREATE INDEX idx_visits_agent ON visits(agent_id);
CREATE INDEX idx_visits_client ON visits(client_id);
CREATE INDEX idx_visits_contract ON visits(contract_id);;

-- lifted circular FK (contracts.quote_id -> invoices.id)
ALTER TABLE contracts ADD CONSTRAINT contracts_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES invoices(id) ON DELETE SET NULL;
