-- =====================================================================
-- HARDENING THE TRIAL PORTAL
--
-- The demo is a login handed to strangers. Four things were wrong, all
-- found by attacking it rather than by reading it:
--
--   1. demo_reset() was granted to `authenticated`, so ANY signed-in
--      account could wipe and restore the whole database. The client
--      portal login did it in a test — mid-presentation that is a dead
--      demo, and it is a free denial-of-service for anyone with the link.
--   2. The trial account is role='admin', and app_has_perm() short-circuits
--      admin to `true` before it looks at per-user overrides. So a prospect
--      could DELETE the permission matrix (75 manager rows went in one
--      request), edit staff accounts, and change company settings.
--   3. users.password_hash and users.token_version were column-readable by
--      every signed-in user. They are empty in this demo, so nothing leaked
--      — but the same policy shape on a real deployment hands out hashes.
--   4. No cap on a single read, so `?limit=100000` returns the table.
--      (The row cap itself is a PostgREST setting, applied by
--      tools/harden.js — it cannot be set from SQL.)
--
-- What this file does NOT pretend to fix: app.js is 863 KB of the real
-- front end and is served to every visitor's browser. It can be read and
-- saved by anyone who opens devtools. Nothing here changes that, and no
-- amount of obfuscation would.
-- =====================================================================

-- ---------------------------------------------------------------- 1 & 2
-- An explicit per-user permission row now beats the admin short-circuit.
-- A row in user_permissions is a deliberate statement about ONE person and
-- is more specific than a role default, so it should win — including over
-- 'admin'. That is what makes it possible to hand out an admin-shaped
-- account with specific powers withheld.
CREATE OR REPLACE FUNCTION app_has_perm(p text) RETURNS boolean
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS
$fn$
  SELECT COALESCE(
    -- explicit, per-user, wins over everything
    (SELECT up.allowed = 1 FROM user_permissions up
      WHERE up.user_id = app_uid() AND up.perm = p),
    CASE WHEN app_role() = 'admin' THEN true
         ELSE (SELECT rp.allowed = 1 FROM role_permissions rp
                WHERE rp.role = app_role() AND rp.perm = p) END,
    false)
$fn$;

-- my_permissions() drives what the UI offers. It has to agree with
-- app_has_perm() exactly, or the trial user is shown buttons that then fail.
CREATE OR REPLACE FUNCTION my_permissions() RETURNS jsonb
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS
$fn$
  SELECT COALESCE((
    SELECT jsonb_object_agg(perm, allowed)
      FROM (
        SELECT rp.perm,
               COALESCE(
                 (SELECT up.allowed = 1 FROM user_permissions up
                   WHERE up.perm = rp.perm AND up.user_id = app_uid()),
                 CASE WHEN app_role() = 'admin' THEN true
                      ELSE rp.allowed = 1 END) AS allowed
          FROM (SELECT DISTINCT perm FROM role_permissions) all_perms
          JOIN role_permissions rp
            ON rp.perm = all_perms.perm
           AND rp.role = CASE WHEN app_role() = 'admin' THEN 'admin' ELSE app_role() END
      ) x), '{}'::jsonb)
$fn$;

-- ---- what the trial account may NOT do -------------------------------
-- It keeps the whole operational system: clients, branches, the diary,
-- dispatch, reports, invoices, devices, analytics. What it loses is the
-- power to damage the demo for the next visitor or to reach the machinery
-- underneath: staff accounts, the permission matrix, company settings.
INSERT INTO user_permissions (user_id, perm, allowed)
SELECT u.id, p, 0
FROM users u, unnest(ARRAY[
  'users.create','users.edit','users.delete',
  'permissions.view','permissions.edit',
  'settings.edit'
]) p
WHERE u.email = 'trial@demo.foxcrm.app'
ON CONFLICT (user_id, perm) DO UPDATE SET allowed = 0;

-- ---------------------------------------------------------------- 1
-- demo_reset() belongs to the trial account and nobody else, and it cannot
-- be used as a hammer: one reset every 10 seconds is plenty for a person
-- signing in and out, and useless as a way to keep the database busy.
CREATE TABLE IF NOT EXISTS demo_reset_log (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reset_at   timestamptz NOT NULL DEFAULT now(),
  by_email   text
);
ALTER TABLE demo_reset_log ENABLE ROW LEVEL SECURITY;
-- No policy: nobody reads it through PostgREST. demo_reset() is SECURITY
-- DEFINER and writes to it as the owner.

CREATE OR REPLACE FUNCTION demo_reset() RETURNS jsonb
  LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS
$fn$
DECLARE
  t     text;
  r     record;
  n     int := 0;
  email text;
  last  timestamptz;
BEGIN
  -- Only the trial account. Every other login — including admin — is
  -- refused, so no demo account can wipe the database out from under
  -- someone who is presenting from it.
  SELECT u.email INTO email FROM users u WHERE u.id = app_uid();
  IF email IS DISTINCT FROM 'trial@demo.foxcrm.app' THEN
    RAISE EXCEPTION 'Not permitted';
  END IF;

  SELECT max(l.reset_at) INTO last FROM demo_reset_log l;
  IF last IS NOT NULL AND last > now() - interval '10 seconds' THEN
    RETURN jsonb_build_object('ok', true, 'skipped', 'just reset', 'at', now_cairo());
  END IF;

  SET CONSTRAINTS ALL DEFERRED;

  SELECT string_agg(format('public.%I', tablename), ', ')
    INTO t FROM pg_tables
   WHERE schemaname = 'public' AND tablename <> 'demo_reset_log';
  EXECUTE 'TRUNCATE TABLE ' || t;

  FOR t IN SELECT tablename FROM pg_tables
            WHERE schemaname = 'public' AND tablename <> 'demo_reset_log'
  LOOP
    EXECUTE format('INSERT INTO public.%I SELECT * FROM demo_snapshot.%I', t, t);
    n := n + 1;
  END LOOP;

  FOR r IN SELECT seq, last_value FROM demo_snapshot._sequences WHERE seq IS NOT NULL
  LOOP
    EXECUTE format('SELECT setval(%L, %s)', r.seq, GREATEST(r.last_value, 1));
  END LOOP;

  INSERT INTO demo_reset_log(by_email) VALUES (email);
  RETURN jsonb_build_object('ok', true, 'tables', n, 'at', now_cairo());
END
$fn$;

REVOKE ALL ON FUNCTION demo_reset() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION demo_reset() TO authenticated;   -- the function itself checks who

-- ---------------------------------------------------------------- 3
-- Credential columns are not readable by anyone through the API, whatever
-- their role. The app never needs them: Supabase Auth owns credentials now.
REVOKE SELECT (password_hash, token_version) ON public.users FROM anon, authenticated;
REVOKE UPDATE (password_hash, token_version, auth_id) ON public.users FROM anon, authenticated;

-- v_users carried auth_id so the shim could find the caller's profile.
-- That is the one GoTrue identifier tying a row to a login, and it has no
-- business on the wire; my_profile() answers the same question without it.
CREATE OR REPLACE FUNCTION my_profile() RETURNS jsonb
  LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS
$fn$
  SELECT to_jsonb(v) - 'auth_id' || jsonb_build_object('permissions', my_permissions())
    FROM v_users v
   WHERE v.id = app_uid()
$fn$;

-- ---- storage: no unbounded uploads -----------------------------------
-- A prospect with an upload box and no limit is an unbounded bill. Photos
-- and maps are images, the library takes documents, branding is a logo.
UPDATE storage.buckets SET
  file_size_limit = 5242880,                                    -- 5 MB
  allowed_mime_types = ARRAY['image/jpeg','image/png','image/webp','image/gif']
WHERE id IN ('photos', 'branding');

UPDATE storage.buckets SET
  file_size_limit = 10485760,                                   -- 10 MB
  allowed_mime_types = ARRAY['image/jpeg','image/png','image/webp','application/pdf']
WHERE id = 'maps';

UPDATE storage.buckets SET
  file_size_limit = 10485760,                                   -- 10 MB
  allowed_mime_types = ARRAY['application/pdf','image/jpeg','image/png',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']
WHERE id = 'documents';


-- ---- keep the reset's own log out of the snapshot ---------------------
-- demo_reset() already skips demo_reset_log when emptying and refilling,
-- but the sequence-restore loop was still rewinding ITS identity counter to
-- whatever the snapshot held, so the very next INSERT into it collided on
-- the primary key and rolled the whole reset back. The log is the audit
-- trail OF the reset; it is neither snapshotted nor restored.
CREATE OR REPLACE FUNCTION demo_snapshot_take() RETURNS text
  LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS
\$
DECLARE t text; n int := 0;
BEGIN
  FOR t IN SELECT tablename FROM pg_tables
            WHERE schemaname = 'public' AND tablename <> 'demo_reset_log'
            ORDER BY tablename
  LOOP
    EXECUTE format('DROP TABLE IF EXISTS demo_snapshot.%I', t);
    EXECUTE format('CREATE TABLE demo_snapshot.%I AS TABLE public.%I', t, t);
    n := n + 1;
  END LOOP;

  DROP TABLE IF EXISTS demo_snapshot._sequences;
  CREATE TABLE demo_snapshot._sequences AS
    SELECT c.table_name, c.column_name,
           pg_get_serial_sequence(c.table_name, c.column_name) AS seq,
           COALESCE((SELECT last_value FROM pg_sequences s
                      WHERE s.schemaname = 'public'
                        AND s.sequencename = split_part(
                              pg_get_serial_sequence(c.table_name, c.column_name), '.', 2)), 1) AS last_value
      FROM information_schema.columns c
     WHERE c.table_schema = 'public' AND c.is_identity = 'YES'
       AND c.table_name <> 'demo_reset_log';
  RETURN n || ' tables snapshotted';
END
\$;
REVOKE ALL ON FUNCTION demo_snapshot_take() FROM PUBLIC, anon, authenticated;

-- ---- the trial account is a MANAGER, not an admin ---------------------
-- app.js's own can() short-circuits role === 'admin' to true, so an
-- admin-shaped trial account is offered every menu item however the server
-- is configured — the prospect clicks Permissions and gets an error rather
-- than a screen. app.js is not ours to change, so the account has to be a
-- role whose permission map the UI will actually consult.
--
-- `manager` is almost exactly right already: the whole operational system
-- including analytics, and it natively lacks finance.* (unported anyway),
-- permissions.* and schedule.clear_all — the last being a "clear the entire
-- diary" button no stranger should hold.
UPDATE users SET role = 'manager' WHERE email = 'trial@demo.foxcrm.app';

INSERT INTO user_permissions (user_id, perm, allowed)
SELECT u.id, x.perm, x.allowed
FROM users u, (VALUES
  ('permissions.view', 1),      -- read the matrix: the RBAC system sells itself
  ('permissions.edit', 0),
  ('users.create',     0),
  ('users.edit',       0),
  ('users.delete',     0),
  ('settings.edit',    0)
) AS x(perm, allowed)
WHERE u.email = 'trial@demo.foxcrm.app'
ON CONFLICT (user_id, perm) DO UPDATE SET allowed = excluded.allowed;
