-- =====================================================================
-- TRIAL SESSIONS: concurrent prospects, and a history of what each did.
--
-- Two problems, demonstrated rather than assumed:
--
--   1. The reset fired on every trial LOGIN. So when a second prospect
--      arrived, the first one's work vanished mid-session — they had a
--      client on screen that stopped existing.
--   2. There was one trial login, so "two prospects" meant two people
--      sharing an account and seeing each other's edits.
--
-- (1) is fixed here properly: the sandbox is reset only when the LAST
-- trial session ends. While anyone is still working, nothing is wiped.
--
-- (2) is fixed only halfway, and it is worth being plain about. Several
-- trial accounts now exist so each prospect has their own login and their
-- own history — but they still share ONE dataset. Two people testing at
-- the same time will see each other's clients and visits. True isolation
-- would need a copy of every row per session, and every table's primary
-- key and foreign keys reworked to carry the session; that is a schema
-- change to all 60 tables, not a demo feature. If a prospect must not see
-- another's work, give them their own Supabase project.
-- =====================================================================

-- ---- the log tables. These OUTLIVE the reset ------------------------
-- The whole point is to answer "what did that prospect do?" after they
-- have gone, so they are excluded from the truncate, the restore and the
-- snapshot. Not exposed to PostgREST either — admin reads them through a
-- function that checks the role.
CREATE TABLE IF NOT EXISTS trial_sessions (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      bigint,
  email        text,
  started_at   timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  ended_at     timestamptz,
  ended_reason text,                       -- signout | idle
  user_agent   text,
  actions      int NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_trial_sessions_live
  ON trial_sessions(last_seen_at) WHERE ended_at IS NULL;

CREATE TABLE IF NOT EXISTS trial_activity (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id bigint REFERENCES trial_sessions(id) ON DELETE CASCADE,
  at         timestamptz NOT NULL DEFAULT now(),
  op         text,
  table_name text,
  row_id     text,
  summary    text
);
CREATE INDEX IF NOT EXISTS idx_trial_activity_session ON trial_activity(session_id, id);

ALTER TABLE trial_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE trial_activity ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON trial_sessions, trial_activity FROM anon, authenticated;

-- How long a session with no activity is still considered live.
CREATE OR REPLACE FUNCTION trial_idle_minutes() RETURNS int
  LANGUAGE sql IMMUTABLE AS $fn$ SELECT 20 $fn$;

-- Retire sessions nobody is using any more, and report how many are left.
CREATE OR REPLACE FUNCTION trial_reap() RETURNS int
  LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS
$fn$
DECLARE live int;
BEGIN
  UPDATE trial_sessions
     SET ended_at = last_seen_at, ended_reason = 'idle'
   WHERE ended_at IS NULL
     AND last_seen_at < now() - make_interval(mins => trial_idle_minutes());
  SELECT count(*) INTO live FROM trial_sessions WHERE ended_at IS NULL;
  RETURN live;
END
$fn$;

-- ---- what the prospect did ------------------------------------------
-- One AFTER trigger on every operational table. It fires only for the
-- `trial` role, and is suppressed while demo_reset() is refilling the
-- database — otherwise a reset would log seven hundred "inserts" that no
-- human performed.
CREATE OR REPLACE FUNCTION trial_log() RETURNS trigger
  LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS
$fn$
DECLARE
  sid  bigint;
  j    jsonb;
  name text;
BEGIN
  IF app_role() IS DISTINCT FROM 'trial' THEN RETURN NULL; END IF;
  IF COALESCE(current_setting('app.trial_suppress', true), '') = 'on' THEN RETURN NULL; END IF;

  SELECT s.id INTO sid FROM trial_sessions s
   WHERE s.user_id = app_uid() AND s.ended_at IS NULL
   ORDER BY s.id DESC LIMIT 1;
  IF sid IS NULL THEN RETURN NULL; END IF;   -- activity outside a session

  j := to_jsonb(COALESCE(NEW, OLD));
  -- Whatever this row calls itself, so the history reads like English
  -- rather than a list of ids.
  name := COALESCE(j ->> 'name_en', j ->> 'name', j ->> 'full_name',
                   j ->> 'code', j ->> 'number', j ->> 'title');

  INSERT INTO trial_activity(session_id, op, table_name, row_id, summary)
  VALUES (sid, TG_OP, TG_TABLE_NAME, j ->> 'id',
          CASE TG_OP WHEN 'INSERT' THEN 'added'
                     WHEN 'UPDATE' THEN 'changed'
                     ELSE 'deleted' END
          || ' ' || TG_TABLE_NAME
          || COALESCE(' — ' || name, ''));

  UPDATE trial_sessions
     SET last_seen_at = now(), actions = actions + 1
   WHERE id = sid;
  RETURN NULL;
END
$fn$;

-- Attach it everywhere except the logs themselves.
DO $mk$
DECLARE t text;
BEGIN
  FOR t IN SELECT tablename FROM pg_tables
            WHERE schemaname = 'public'
              AND tablename NOT IN ('trial_sessions','trial_activity',
                                    'demo_reset_log','audit_log')
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS trg_trial_log ON public.%I', t);
    EXECUTE format('CREATE TRIGGER trg_trial_log AFTER INSERT OR UPDATE OR DELETE '
                   'ON public.%I FOR EACH ROW EXECUTE FUNCTION trial_log()', t);
  END LOOP;
END
$mk$;

-- ---- the session lifecycle ------------------------------------------
-- Opening a session resets the sandbox ONLY if nobody else is working in
-- it. That is the whole fix for the mid-session wipe: an arriving prospect
-- no longer destroys the one already there.
CREATE OR REPLACE FUNCTION trial_session_start(p_user_agent text DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS
$fn$
DECLARE live int; sid bigint; did_reset boolean := false;
BEGIN
  IF app_role() IS DISTINCT FROM 'trial' THEN
    RAISE EXCEPTION 'Not permitted';
  END IF;

  -- Close my own previous session first: signing in again is a new visit.
  UPDATE trial_sessions SET ended_at = now(), ended_reason = 'signout'
   WHERE user_id = app_uid() AND ended_at IS NULL;

  live := trial_reap();
  IF live = 0 THEN
    PERFORM demo_reset();
    did_reset := true;
  END IF;

  INSERT INTO trial_sessions(user_id, email, user_agent)
  VALUES (app_uid(),
          (SELECT u.email FROM users u WHERE u.id = app_uid()),
          left(COALESCE(p_user_agent, ''), 300))
  RETURNING id INTO sid;

  RETURN jsonb_build_object('session_id', sid, 'reset', did_reset,
                            'others_live', live);
END
$fn$;

-- Ending the last live session is what actually cleans the sandbox.
CREATE OR REPLACE FUNCTION trial_session_end() RETURNS jsonb
  LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS
$fn$
DECLARE live int; did_reset boolean := false;
BEGIN
  IF app_role() IS DISTINCT FROM 'trial' THEN
    RAISE EXCEPTION 'Not permitted';
  END IF;

  UPDATE trial_sessions SET ended_at = now(), ended_reason = 'signout'
   WHERE user_id = app_uid() AND ended_at IS NULL;

  live := trial_reap();
  IF live = 0 THEN
    PERFORM demo_reset();
    did_reset := true;
  END IF;
  RETURN jsonb_build_object('ok', true, 'reset', did_reset, 'others_live', live);
END
$fn$;

REVOKE ALL ON FUNCTION trial_session_start(text), trial_session_end() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION trial_session_start(text), trial_session_end() TO authenticated;

-- ---- demo_reset: leave the logs alone, and stay quiet ---------------
CREATE OR REPLACE FUNCTION demo_reset() RETURNS jsonb
  LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS
$fn$
DECLARE t text; r record; n int := 0; who text; last timestamptz;
BEGIN
  IF app_role() IS DISTINCT FROM 'trial' THEN
    RAISE EXCEPTION 'Not permitted';
  END IF;
  SELECT u.email INTO who FROM users u WHERE u.id = app_uid();

  SELECT max(l.reset_at) INTO last FROM demo_reset_log l;
  IF last IS NOT NULL AND last > now() - interval '10 seconds' THEN
    RETURN jsonb_build_object('ok', true, 'skipped', 'just reset', 'at', now_cairo());
  END IF;

  -- The restore is not the prospect's work; do not log seven hundred rows.
  PERFORM set_config('app.trial_suppress', 'on', true);
  SET CONSTRAINTS ALL DEFERRED;

  SELECT string_agg(format('public.%I', tablename), ', ')
    INTO t FROM pg_tables
   WHERE schemaname = 'public'
     AND tablename NOT IN ('demo_reset_log','trial_sessions','trial_activity');
  EXECUTE 'TRUNCATE TABLE ' || t;

  FOR t IN SELECT tablename FROM pg_tables
            WHERE schemaname = 'public'
              AND tablename NOT IN ('demo_reset_log','trial_sessions','trial_activity')
  LOOP
    EXECUTE format('INSERT INTO public.%I SELECT * FROM demo_snapshot.%I', t, t);
    n := n + 1;
  END LOOP;

  FOR r IN SELECT seq, last_value FROM demo_snapshot._sequences WHERE seq IS NOT NULL
  LOOP
    EXECUTE format('SELECT setval(%L, %s)', r.seq, GREATEST(r.last_value, 1));
  END LOOP;

  PERFORM set_config('app.trial_suppress', 'off', true);
  INSERT INTO demo_reset_log(by_email) VALUES (who);
  RETURN jsonb_build_object('ok', true, 'tables', n, 'at', now_cairo());
END
$fn$;
REVOKE ALL ON FUNCTION demo_reset() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION demo_reset() TO authenticated;

-- ...and out of the snapshot, or a restore would resurrect old sessions.
CREATE OR REPLACE FUNCTION demo_snapshot_take() RETURNS text
  LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS
$fn$
DECLARE t text; n int := 0;
BEGIN
  FOR t IN SELECT tablename FROM pg_tables
            WHERE schemaname = 'public'
              AND tablename NOT IN ('demo_reset_log','trial_sessions','trial_activity')
            ORDER BY tablename
  LOOP
    EXECUTE format('DROP TABLE IF EXISTS demo_snapshot.%I', t);
    EXECUTE format('CREATE TABLE demo_snapshot.%I AS TABLE public.%I', t, t);
    n := n + 1;
  END LOOP;

  DROP TABLE IF EXISTS demo_snapshot._sequences;
  CREATE TABLE demo_snapshot._sequences AS
    SELECT c.table_name, c.column_name,
           pg_get_serial_sequence(c.table_name, c.column_name) AS seq,
           COALESCE((SELECT last_value FROM pg_sequences s
                      WHERE s.schemaname = 'public'
                        AND s.sequencename = split_part(
                              pg_get_serial_sequence(c.table_name, c.column_name), '.', 2)), 1) AS last_value
      FROM information_schema.columns c
     WHERE c.table_schema = 'public' AND c.is_identity = 'YES'
       AND c.table_name NOT IN ('demo_reset_log','trial_sessions','trial_activity');
  RETURN n || ' tables snapshotted';
END
$fn$;
REVOKE ALL ON FUNCTION demo_snapshot_take() FROM PUBLIC, anon, authenticated;


-- ---- what the office sees -------------------------------------------
-- Admin-only, by role rather than by permission: this is an operator tool
-- about the demo itself, not a feature of the product.
CREATE OR REPLACE FUNCTION trial_sessions_list(p_limit int DEFAULT 100)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS
$fn$
BEGIN
  IF app_role() <> 'admin' THEN RAISE EXCEPTION 'Not permitted'; END IF;
  RETURN COALESCE((
    SELECT jsonb_agg(to_jsonb(x) ORDER BY x.started_at DESC)
      FROM (SELECT s.id, s.email, s.started_at, s.last_seen_at, s.ended_at,
                   s.ended_reason, s.actions, s.user_agent,
                   (s.ended_at IS NULL
                    AND s.last_seen_at > now() - make_interval(mins => trial_idle_minutes()))
                     AS live,
                   round(EXTRACT(epoch FROM
                     COALESCE(s.ended_at, s.last_seen_at) - s.started_at) / 60.0, 1) AS minutes
              FROM trial_sessions s
             ORDER BY s.started_at DESC
             LIMIT GREATEST(1, LEAST(p_limit, 500))) x), '[]'::jsonb);
END
$fn$;

CREATE OR REPLACE FUNCTION trial_session_activity(p_session_id bigint,
                                                  p_limit int DEFAULT 500)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS
$fn$
BEGIN
  IF app_role() <> 'admin' THEN RAISE EXCEPTION 'Not permitted'; END IF;
  RETURN jsonb_build_object(
    'session', (SELECT to_jsonb(s) FROM trial_sessions s WHERE s.id = p_session_id),
    'items', COALESCE((
      SELECT jsonb_agg(to_jsonb(a) ORDER BY a.id)
        FROM (SELECT id, at, op, table_name, row_id, summary
                FROM trial_activity
               WHERE session_id = p_session_id
               ORDER BY id
               LIMIT GREATEST(1, LEAST(p_limit, 2000))) a), '[]'::jsonb),
    -- what they spent their time on, which is the useful summary
    'by_table', COALESCE((
      SELECT jsonb_agg(jsonb_build_object('table_name', t, 'n', n) ORDER BY n DESC)
        FROM (SELECT table_name t, count(*) n FROM trial_activity
               WHERE session_id = p_session_id GROUP BY table_name) q), '[]'::jsonb));
END
$fn$;

REVOKE ALL ON FUNCTION trial_sessions_list(int), trial_session_activity(bigint, int)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION trial_sessions_list(int), trial_session_activity(bigint, int)
  TO authenticated;


-- ---- the throttle must not swallow the cleanup ----------------------
-- demo_reset() refuses to run twice within ten seconds, which was right
-- when every login called it. Now that the reset is driven by the session
-- lifecycle it fires rarely — and the one call that MUST land is the last
-- prospect signing out. In testing that call arrived nine seconds after the
-- previous one, was silently skipped, and the next visitor inherited the
-- last one's company while trial_session_end() cheerfully reported success.
--
-- So: the lifecycle path sets a transaction-local flag that bypasses the
-- throttle, and demo_reset() now REPORTS whether it actually ran instead of
-- letting the caller assume. A trial user calling demo_reset() by hand
-- still meets the throttle — the flag is not something a request can set.
CREATE OR REPLACE FUNCTION demo_reset() RETURNS jsonb
  LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS
$fn$
DECLARE t text; r record; n int := 0; who text; last timestamptz;
        forced boolean := COALESCE(current_setting('app.trial_force_reset', true), '') = 'on';
BEGIN
  IF app_role() IS DISTINCT FROM 'trial' THEN
    RAISE EXCEPTION 'Not permitted';
  END IF;
  SELECT u.email INTO who FROM users u WHERE u.id = app_uid();

  SELECT max(l.reset_at) INTO last FROM demo_reset_log l;
  IF NOT forced AND last IS NOT NULL AND last > now() - interval '10 seconds' THEN
    RETURN jsonb_build_object('ok', true, 'reset', false,
                              'skipped', 'just reset', 'at', now_cairo());
  END IF;

  PERFORM set_config('app.trial_suppress', 'on', true);
  SET CONSTRAINTS ALL DEFERRED;

  SELECT string_agg(format('public.%I', tablename), ', ')
    INTO t FROM pg_tables
   WHERE schemaname = 'public'
     AND tablename NOT IN ('demo_reset_log','trial_sessions','trial_activity');
  EXECUTE 'TRUNCATE TABLE ' || t;

  FOR t IN SELECT tablename FROM pg_tables
            WHERE schemaname = 'public'
              AND tablename NOT IN ('demo_reset_log','trial_sessions','trial_activity')
  LOOP
    EXECUTE format('INSERT INTO public.%I SELECT * FROM demo_snapshot.%I', t, t);
    n := n + 1;
  END LOOP;

  FOR r IN SELECT seq, last_value FROM demo_snapshot._sequences WHERE seq IS NOT NULL
  LOOP
    EXECUTE format('SELECT setval(%L, %s)', r.seq, GREATEST(r.last_value, 1));
  END LOOP;

  PERFORM set_config('app.trial_suppress', 'off', true);
  INSERT INTO demo_reset_log(by_email) VALUES (who);
  RETURN jsonb_build_object('ok', true, 'reset', true, 'tables', n, 'at', now_cairo());
END
$fn$;
REVOKE ALL ON FUNCTION demo_reset() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION demo_reset() TO authenticated;

CREATE OR REPLACE FUNCTION trial_session_start(p_user_agent text DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS
$fn$
DECLARE live int; sid bigint; res jsonb := NULL;
BEGIN
  IF app_role() IS DISTINCT FROM 'trial' THEN
    RAISE EXCEPTION 'Not permitted';
  END IF;

  UPDATE trial_sessions SET ended_at = now(), ended_reason = 'signout'
   WHERE user_id = app_uid() AND ended_at IS NULL;

  live := trial_reap();
  IF live = 0 THEN
    PERFORM set_config('app.trial_force_reset', 'on', true);
    res := demo_reset();
    PERFORM set_config('app.trial_force_reset', 'off', true);
  END IF;

  INSERT INTO trial_sessions(user_id, email, user_agent)
  VALUES (app_uid(),
          (SELECT u.email FROM users u WHERE u.id = app_uid()),
          left(COALESCE(p_user_agent, ''), 300))
  RETURNING id INTO sid;

  RETURN jsonb_build_object('session_id', sid,
                            'reset', COALESCE((res ->> 'reset')::boolean, false),
                            'others_live', live);
END
$fn$;

CREATE OR REPLACE FUNCTION trial_session_end() RETURNS jsonb
  LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS
$fn$
DECLARE live int; res jsonb := NULL;
BEGIN
  IF app_role() IS DISTINCT FROM 'trial' THEN
    RAISE EXCEPTION 'Not permitted';
  END IF;

  UPDATE trial_sessions SET ended_at = now(), ended_reason = 'signout'
   WHERE user_id = app_uid() AND ended_at IS NULL;

  live := trial_reap();
  IF live = 0 THEN
    PERFORM set_config('app.trial_force_reset', 'on', true);
    res := demo_reset();
    PERFORM set_config('app.trial_force_reset', 'off', true);
  END IF;
  RETURN jsonb_build_object('ok', true,
                            'reset', COALESCE((res ->> 'reset')::boolean, false),
                            'others_live', live);
END
$fn$;
REVOKE ALL ON FUNCTION trial_session_start(text), trial_session_end() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION trial_session_start(text), trial_session_end() TO authenticated;
